### ISSUE TITLE
Line numbers in Ant experiment

### ISSUE THREAD

**Issue by neale** [nnaisense/max#2]
Hi, 

It looks like in order to run the Ant experiments we need to enable the coverage metric. 
The readme says to:
* Uncomment lines 474-481 and comment out lines 483-506 in main.py.

I think it should be 
* Uncomment lines 482-487 and comment out lines 489-512 in main.py.

Is that right? 

Also, if I visualize the ant experiment, it looks like the ant quickly learns to explore deep into the maze, as expected. But the coverage reported is very low -- maybe 5 - 10% after 4000 iterations. Why is this?

**Comment by wjaskowski** [comment]
The coverage is heavily discretized. The number means the number of blocks covered. The maze consists of 7 large blocks, so 7 means 100%.

I have just fixed the lines number issue (36d9ed6bc4)

**Comment by neale** [comment]
Thanks!
