### ISSUE TITLE
Reproducing figure on Maze Exploration Performance

### ISSUE THREAD

**Issue by johnmoberg** [nnaisense/max#3]
I'm trying to reproduce Figure 2(b) from the paper and I can't see where the maze coverage % comes from. In the code, it looks like the maze is discretized into seven blocks and coverage is reported in terms of # of blocks visited, but this cannot correspond to the percentages reported in the figure unless I'm missing something. Thank you.

**Comment by pranv** [comment]
Hi,

Thanks for your interest in our work. The plotted percentages are # of visited blocks / total # of blocks (which is 7). I'm not sure why you say "this cannot correspond to the percentages reported in the figure". Could you please elaborate?

**Comment by johnmoberg** [comment]
Thank you for doing it, very interesting work! If I look at the % reported for MAX, I see something like 25%, 60%, 70%, 84%, 90%, 91%, 92% for 256, 1500, 3000, ..., 9000 steps, which aren't multiples of 1/7, and similarly for the other methods. Perhaps I'm misunderstanding something?

**Comment by johnmoberg** [comment]
Oh, I'm sorry, is that just because it is the mean over 8 runs? How stupid of me...

**Comment by pranv** [comment]
The % numbers are averages of 8 runs. So they need not be multiples of 7.

**Comment by pranv** [comment]
No worries, thanks for your interest and let us know if you have any questions :)
